name: CI Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

        with:
          # Copy full history
          fetch-depth: 0
          # Optionally, ensure the ref is set for pull requests
          ref: ${{ github.head_ref }}

        # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: install dependencies
        run: npm ci --legacy-peer-deps
      - name: test screenshots
        run: npm run screenshot:compare
      - name: Leave a PR comment
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const filePath = path.join(process.cwd(), '.reg/out.json');
            
            if (!fs.existsSync(filePath)) {
              throw new Error(`File not found: ${filePath}`);
            }
            
            const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            
            const body = `ðŸ‘‹ Thanks for **reporting**! \n
              <b>${JSON.stringify(data)}</b>`;
            
            console.log('info', context);
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              body
            })
